use std::fmt::Display;
use validator::ValidateEmail;

#[derive(Debug, Clone)]
pub struct SubscriberEmailAddress(String);

impl Display for SubscriberEmailAddress {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl SubscriberEmailAddress {
    pub fn parse(s: String) -> Result<SubscriberEmailAddress, String> {
        if s.validate_email() {
            Ok(Self(s))
        } else {
            Err("Email is invalid".to_string())
        }
    }
}

impl AsRef<str> for SubscriberEmailAddress {
    fn as_ref(&self) -> &str {
        &self.0
    }
}

#[cfg(test)]
mod tests {
    use super::SubscriberEmailAddress;
    use claims::{assert_err, assert_ok};
    use rand::SeedableRng;
    use rand::rngs::StdRng;
    // We are importing the `SafeEmail` faker!
    // We also need the `Fake` trait to get access to the
    // `.fake` method on `SafeEmail`
    use fake::Fake;
    use fake::faker::internet::en::SafeEmail;

    #[derive(Debug, Clone)]
    struct ValidEmailFixture(pub String);

    impl quickcheck::Arbitrary for ValidEmailFixture {
        fn arbitrary(g: &mut quickcheck::Gen) -> Self {
            // We get `quickcheck` and `fake` to interoperate via the `rand` crate.
            // We create a seed from a random `u64` generated by `quickcheck`'s `Gen`,
            // which is in turn determined by `quickcheck`'s own seed.
            // We then use this seed to create a new random number generator, which
            // we pass to `fake`'s `SafeEmail`.
            // This way we can generate a random valid email every time `quickcheck`
            // calls `arbitrary`, and the generation process is deterministic for
            // a given seed.
            let mut rng = StdRng::seed_from_u64(u64::arbitrary(g));
            let email = SafeEmail().fake_with_rng(&mut rng);

            Self(email)
        }
    }

    #[test]
    fn empty_string_is_rejected() {
        let email = "".to_string();
        assert_err!(SubscriberEmailAddress::parse(email));
    }
    #[test]
    fn email_missing_at_symbol_is_rejected() {
        let email = "ursuladomain.com".to_string();
        assert_err!(SubscriberEmailAddress::parse(email));
    }

    #[test]
    fn email_missing_subject_is_rejected() {
        let email = "@domain.com".to_string();
        assert_err!(SubscriberEmailAddress::parse(email));
    }

    #[test]
    fn a_valid_email_is_parsed_successfully() {
        let email = "ursula@domain.com".to_string();
        assert_ok!(SubscriberEmailAddress::parse(email));
    }

    #[test]
    fn random_valid_emails_are_parsed_successfully() {
        let email = SafeEmail().fake();
        claims::assert_ok!(SubscriberEmailAddress::parse(email));
    }

    #[quickcheck_macros::quickcheck]
    fn valid_emails_are_parsed_successfully(valid_email: ValidEmailFixture) -> bool {
        dbg!(&valid_email.0);
        SubscriberEmailAddress::parse(valid_email.0).is_ok()
    }
}
